CREATE OR REPLACE FUNCTION CHAIN1.FNC_GRAPHNODE_BLOCK_REMOVE ()
RETURNS TRIGGER
LANGUAGE PLPGSQL
AS $$
BEGIN
	IF NEW.NUMBER > 5000 AND MOD(NEW.NUMBER, 1000) = 0 THEN
        DELETE
        FROM    CHAIN1.BLOCKS
        WHERE   NUMBER <= NEW.NUMBER - 5000;
    END IF;

	RETURN NULL;
END;
$$;

--------------------------------------------------------

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM PG_TRIGGER WHERE TGNAME = 'trg_graphnode_block_remove') THEN
        RETURN;
    END IF;

    CREATE TRIGGER trg_graphnode_block_remove
    AFTER INSERT
    ON CHAIN1.BLOCKS
    FOR EACH ROW
    EXECUTE PROCEDURE CHAIN1.FNC_GRAPHNODE_BLOCK_REMOVE();
END
$$;