CREATE TABLE IF NOT EXISTS BACKEND.MATCHED_ORDERS_HISTORY (
    NFT_CONTRACT	    VARCHAR(50)     NOT NULL,
    TOKEN_ID	        BIGINT          NOT NULL,
    SELLER	            VARCHAR(50)     NOT NULL,
    BUYER	            VARCHAR(50)     NOT NULL,
    PRICE	            NUMERIC         NOT NULL,
    CURRENCY_CONTRACT	VARCHAR(50)     NOT NULL,
    TYPE	            VARCHAR(20)     NOT NULL,
    TRANSACTION         VARCHAR(100)    NOT NULL,
    TRANSACTION_TIME    BIGINT          NOT NULL,
    CREATED_AT	        TIMESTAMP	    DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (NFT_CONTRACT, TOKEN_ID, TRANSACTION)
);

CREATE INDEX IF NOT EXISTS IDX_MATCHED_ORDERS_HISTORY_SELLER            ON BACKEND.MATCHED_ORDERS_HISTORY (SELLER);
CREATE INDEX IF NOT EXISTS IDX_MATCHED_ORDERS_HISTORY_BUYER             ON BACKEND.MATCHED_ORDERS_HISTORY (BUYER);
CREATE INDEX IF NOT EXISTS IDX_MATCHED_ORDERS_HISTORY_CURRENCY_CONTRACT ON BACKEND.MATCHED_ORDERS_HISTORY (CURRENCY_CONTRACT);