CREATE TABLE IF NOT EXISTS BACKEND.SELL_ORDERS_HISTORY (
    NFT_CONTRACT	    VARCHAR(50)     NOT NULL,
    TOKEN_ID	        BIGINT          NOT NULL,
    SELLER	            VARCHAR(50)     NOT NULL,
    PRICE	            NUMERIC         NOT NULL,
    CURRENCY_CONTRACT	VARCHAR(50)     NOT NULL,
    STATUS	            BOOLEAN         NOT NULL,   -- TRUE: OPEN, FALSE: CLOSE
    TRANSACTION         VARCHAR(100)    NOT NULL,
    TRANSACTION_TIME    BIGINT          NOT NULL,
    CREATED_AT	        TIMESTAMP	    DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (NFT_CONTRACT, TOKEN_ID, TRANSACTION)
);

CREATE INDEX IF NOT EXISTS IDX_SELL_ORDERS_HISTORY_SELLER               ON BACKEND.SELL_ORDERS_HISTORY (SELLER);
CREATE INDEX IF NOT EXISTS IDX_SELL_ORDERS_HISTORY_CURRENCY_CONTRACT    ON BACKEND.SELL_ORDERS_HISTORY (CURRENCY_CONTRACT);