CREATE TABLE IF NOT EXISTS BACKEND.SELL_ORDERS (
    NFT_CONTRACT	            VARCHAR(50)     NOT NULL,
    TOKEN_ID	                BIGINT          NOT NULL,
    SELLER	                    VARCHAR(50)     NOT NULL,
    PRICE	                    NUMERIC         NOT NULL,
    CURRENCY_CONTRACT	        VARCHAR(50)     NOT NULL,
    CREATED_AT	                TIMESTAMP	    DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (NFT_CONTRACT, TOKEN_ID)
);

CREATE INDEX IF NOT EXISTS IDX_SELL_ORDERS_SELLER               ON BACKEND.SELL_ORDERS (SELLER);
CREATE INDEX IF NOT EXISTS IDX_SELL_ORDERS_CURRENCY_CONTRACT    ON BACKEND.SELL_ORDERS (CURRENCY_CONTRACT);