CREATE TABLE IF NOT EXISTS BACKEND.SNAKES_HISTORY (
    SNAKE_ID	        BIGINT          NOT NULL,
    USER_FROM           VARCHAR(50)     NOT NULL,
    USER_TO             VARCHAR(50)     NOT NULL,
    TRANSACTION         VARCHAR(100)    NOT NULL,
    TRANSACTION_TIME    BIGINT          NOT NULL,
    CREATED_AT	        TIMESTAMP	    DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (SNAKE_ID, USER_FROM, USER_TO, TRANSACTION)
);

CREATE INDEX IF NOT EXISTS IDX_SNAKES_HISTORY_USER_FROM  ON BACKEND.SNAKES_HISTORY (USER_FROM);
CREATE INDEX IF NOT EXISTS IDX_SNAKES_HISTORY_USER_TO    ON BACKEND.SNAKES_HISTORY (USER_TO);