CREATE TABLE IF NOT EXISTS BACKEND.SNAKES (
    ID	                        BIGINT          NOT NULL,
    CREATOR                     VARCHAR(50)     NOT NULL,
    OWNER                       VARCHAR(50)     NOT NULL,
    LATEST_TRANSACTION_TIME     BIGINT          NOT NULL,
    CREATED_AT	                TIMESTAMP	    DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (ID)
);

CREATE INDEX IF NOT EXISTS IDX_SNAKES_CREATOR    ON BACKEND.SNAKES (CREATOR);
CREATE INDEX IF NOT EXISTS IDX_SNAKES_OWNER      ON BACKEND.SNAKES (OWNER);